void calc_move(CHAR_DATA *ch);
void advance_turn(CHAR_DATA *ch);
void f_multi_hit( CHAR_DATA*ch, CHAR_DATA *victim, int dt );
void generate_random_mountains(ROOM_INDEX_DATA *room);
void handle_reaction(CHAR_DATA *ch, CHAR_DATA *victim);
void generate_random_hills(ROOM_INDEX_DATA *room);
void say_spell(CHAR_DATA *ch, int sn);
void check_winner(ROOM_INDEX_DATA *ro);
void set_stats(CHAR_DATA *ch); //stub
void do_autodisp(CHAR_DATA *ch, char *argument);
void leave_fight(CHAR_DATA *ch);
void gen_random_battle(CHAR_DATA *ch);
void do_test (CHAR_DATA * ch, char *argument);
void do_fdisp (CHAR_DATA * ch, char *argument);
void do_attack (CHAR_DATA * ch, char *argument);
void handle_reaction(CHAR_DATA *ch, CHAR_DATA *victim);
void generate_random_terrain(ROOM_INDEX_DATA *room);
void generate_random_mountains(ROOM_INDEX_DATA *room);
void generate_random_rooms(ROOM_INDEX_DATA *room);
void generate_random_hills(ROOM_INDEX_DATA *room);
void vary(ROOM_INDEX_DATA *room, int i, int j);
void do_join (CHAR_DATA * ch, char *argument);
void do_map (CHAR_DATA * ch, char *argument);
void fmap (CHAR_DATA * ch, bool forced, bool range, char *argument);
void check_winner(ROOM_INDEX_DATA *ro);
void announce_move(CHAR_DATA * ch, char * thedir);
void do_done(CHAR_DATA * ch, char * thedir);
void tile_spell(CHAR_DATA *ch, int sn);
void refresh(ROOM_INDEX_DATA *r);
void advance_turn(CHAR_DATA * ch);
void do_gain(CHAR_DATA *ch, char *argument);
void do_job(CHAR_DATA *ch, char *argument);
void equip_skill(CHAR_DATA *ch, int sn);
void throw_stone (CHAR_DATA * ch, char *argument);
char * get_t_color(CHAR_DATA *ch);char * fcn(CHAR_DATA *ch);CHAR_DATA * find_char_xy(CHAR_DATA *ch, int x, int y);int hdif(CHAR_DATA *ch, int dir);bool is_mastered(CHAR_DATA *ch, int job);int get_w_dmg(CHAR_DATA *ch);void gain_jp (CHAR_DATA * ch, int gain);int find_char_pos(CHAR_DATA *ch, char *arg, int coord);int find_distance(int xt,int yt,int yc,int xc);